baseURL = "https://jcpwriting.github.io/irreconcilable/"
languageCode = "en-us"
title = "irreconcilable"
theme = "PaperMod"

[params]
  description = "a writing project about the gaps between"
  author = "James Cody Phelan"
  
  defaultTheme = "light"  # Changed to light since your CSS defaults to light
  ShowReadingTime = false  # You hid this anyway
  ShowShareButtons = false  # You hid this anyway
  ShowPostNavLinks = false
  ShowBreadCrumbs = false  # You hid this anyway
  ShowCodeCopyButtons = true

  [params.homeInfoParams]
    Title = "irreconcilable"
    Content = "a writing project about the gaps between"

[menu]
  [[menu.main]]
    name = "home"
    url = "/"
    weight = 10
  
  [[menu.main]]
    name = "archive"
    url = "/archive/"
    weight = 20
  
  [[menu.main]]
    name = "the project"
    url = "/the-project/"
    weight = 30