baseURL = "https://farmerjimbo.github.io/blogito/"
languageCode = "en-us"
title = "irreconcilable"
theme = "PaperMod"

[params]
  description = "a writing project about the gaps between"
  author = "James Cody Phelan"
  
  defaultTheme = "dark"  # Dark theme works better for glitchy aesthetic
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = false
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true

  [params.homeInfoParams]
    Title = "irreconcilable"
    Content = "a writing project about the gaps between"

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 10
  
  [[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 20
  
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 30
